apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mailchimp
  namespace: mytardis
spec:
  schedule: "10 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: go
            image: mytardis/mytardis-mailchimp:latest
            imagePullPolicy: Always
            command:
              - python
              - index.py
              - --days=365
            volumeMounts:
            - name: settings
              mountPath: /app/settings.yaml
              subPath: settings.yaml
          volumes:
            - name: settings
              configMap:
                name: mailchimp
